version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:18.14.0
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install node package
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Run Test
#          command: npm test -- src/chapter2/getting_started_vitest src/chapter2/assertion src/chapter2/group src/chapter2/mock
#          command: |
#            TEST_FILES=$(npx vitest src/chapter2/getting_started_vitest src/chapter2/assertion src/chapter2/group src/chapter2/mock --sequence.hook='list' | circleci tests split)
#            echo $TEST_FILES
#            npm test -- $TEST_FILES
          command: |
            npm test -- --shard=$(($CIRCLE_NODE_INDEX+1))/$CIRCLE_NODE_TOTAL src/chapter2/getting_started_vitest src/chapter2/assertion src/chapter2/group src/chapter2/mock
      - store_test_results:
          path: reports/vitest
workflows:
  test:
    jobs:
      - test
