version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - checkout
      - run:
          name: Install node package
          command: npm install
      - run:
          name: Run Test
          command: npm test -- src/chapter2/getting_started_vitest src/chapter2/assertion src/chapter2/group src/chapter2/mock
      - store_test_results:
          path: reports/vitest
workflows:
  test:
    jobs:
      - test
